### ISSUE TITLE
Wait a bit more with versions ;)

### ISSUE THREAD

**Issue by LinguList** [martino-vic/gerstnerhungarian#5]
I would suggest to tie versions to actual publications, or if you prepare one. If you make a version for every smaller change, Zenodo has to work a lot. Our procedure is: we do new versions always when we have an upcoming publication where we want everything to be clearly identifiable with this particular version.

**Comment by martino-vic** [comment]
Ah okay, I see, I didn't know that, thanks for clarifying! Is there anything I can do about this at the moment, or should I just leave it like this and remember for the next time?

**Comment by LinguList** [comment]
Just remember. I can ahare some more thoughts on this via email. We anywaybwanted to discuss how to make some paper of the new workflow, right?

**Comment by martino-vic** [comment]
Deleted the previous versions and renamed the current one to "first version"
