### ISSUE TITLE
create command for terminal

### ISSUE THREAD

**Issue by martino-vic** [martino-vic/gerstnerhungarian#6]
@LinguList added this [script](https://github.com/martino-vic/gerstnerhungarian/blob/main/raw/misc/reconstruct.py) to create backwards reconstructions based on previously extracted [soundchanges](https://github.com/martino-vic/ronatasbertawot/blob/main/etc/soundchanges.txt), see column "rc" in [forms.csv](https://github.com/martino-vic/gerstnerhungarian/blob/main/cldf/forms.csv). Should turn this into a command-line command at one point.

Btw, the recostructions are customisable through the parameters, now I made it so that there are max 10 false positives per word. It is also possible to spell out the combinations and run some filters over it :)

**Comment by LinguList** [comment]
@martino-vic, I just saw, what you probably did not realize immediately, that I already SHOWED you how to make commandline commands. Please check the folder "gerstnerhungariancommands" and the script `map.py` therein. 

This is the basic structure to use to make your individual scripts with the data work!

**Comment by martino-vic** [comment]
Have learned how to make commandline commands now, based on the given example
